services:
  
  menu-webapi:
    container_name: webapi
    image: menu-webapi
    build:
      context: .
      dockerfile: Menu-WebApi/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - menu-network
    depends_on:
      - database
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck || exit 1 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
        
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "5001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - menu-network
    depends_on:
      menu-webapi:
        condition: service_healthy
      
  database:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Amister@4879
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks: 
      - menu-network
    volumes:
      - C:\Docker\Volumes\sql-server\data:/var/opt/mssql/data
      - C:\Docker\Volumes\sql-server\log:/var/opt/mssql/log
      - C:\Docker\Volumes\sql-server\secrets:/var/opt/mssql/secrets
    
networks:
  menu-network:
  