services:
  
  menu-webapi:
    container_name: webapi
    image: menu-webapi
    build:
      context: .
      dockerfile: Menu-WebApi/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - menu-network
    depends_on:
      - database
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck || exit 1 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
        
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "5001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - menu-network
    depends_on:
      menu-webapi:
        condition: service_healthy
      
  database:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Amister@4879
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks: 
      - menu-network
    volumes:
      - C:\Docker\Volumes\sql-server\data:/var/opt/mssql/data
      - C:\Docker\Volumes\sql-server\log:/var/opt/mssql/log
      - C:\Docker\Volumes\sql-server\secrets:/var/opt/mssql/secrets
        
  keycloack:
    container_name: keycloack
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=P@ssword
      - KC_HTTP_PORT=8080
      - KC_HTTPS_PORT=8433
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [ "start-dev"]
    ports:
      - "3000:8080"
      - "3001:8433"  
    networks:
      - menu-network
    
networks:
  menu-network:
  